# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: conf.py

# Install Python packages from PyPI for autodoc
python:
  install:
  - requirements: requirements.txt
  - pip:
      - accuralai-core
      - accuralai-cache
      - accuralai-canonicalize
      - accuralai-google
      - accuralai-ollama
      - accuralai-router
      - accuralai-validator